

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: postgres

production:
  <<: *default
  database: postgres
  username: postgres  
  password: postgres
  host: localhost

